name: Publish
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 7

      - name: Install packages
        run: pnpm install

      - name: Run tests
        run: pnpm test:ci

      - name: Build
        run: pnpm build

      - name: Publish packages
        run: pnpm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
